[versions]
wilderforge_version = "0.6.1.0"
workspace_version = "6.6.0.0"

#Define the library by defining its module and version reference.
[libraries]
wilderforge = { module = "com.wildermods:wilderforge", version.ref = "wilderforge_version" }

#Gradle plugins should be defined here. WilderWorkspace is a gradle plugin.
[plugins]
workspace = { id = "com.wildermods.workspace", version.ref = "workspace_version" }
